services:
  clarkd:
    container_name: clarkd 
    image: test
    restart: unless-stopped
    environment:
      - ARK_ROUND_INTERVAL=10
      - ARK_NETWORK=regtest
      - ARK_LOG_LEVEL=5
      - ARK_ROUND_LIFETIME=512
      - ARK_TX_BUILDER_TYPE=covenantless
      - ARK_ESPLORA_URL=http://chopsticks:3000
      - ARK_NEUTRINO_PEER=bitcoin:18444
      - ARK_NO_TLS=true
      - ARK_NO_MACAROONS=true
      - ARK_DATADIR=/app/data
    ports:
      - "7070:7070"
    volumes:
      - type: tmpfs
        target: /app/data

networks:
  default:
    name: nigiri
    external: true
